### PR TITLE
Fixed set admin_status for deleted subintf due to late notification

### PR DESCRIPTION
**Pull request by EdenGri**
**What I did**
Handled a race condition in intfmgrd which tries to immediately apply an admin_status SET notif after a DEL causing it to crash
**Why I did it**
Ignores errors on the set admin_status command for subinterface when the subinterface state is not OK.

**How I verified it**

**Details if related**
This PR reference to older PR that fix the same issue in portmgr: https://github.com/sonic-net/sonic-swss/pull/2431

### CODE REVIEW

**Comment by vivekrnv** [comment]
the fix is handled in intfmgrd and not portmgrd, the description can be updated.

**Comment by vivekrnv** [comment]
Was the DEL notification seen because the user deleted the iface?

**Comment by EdenGri** [comment]
> Was the DEL notification seen because the user deleted the iface?

A DEL notification arrives after some reboot of the system (cold reboot/config reload).

**Comment by vivekrnv** [comment]
> config

I see, Thanks

**Review by vivekrnv — APPROVED** [review]

**Review by dprital — APPROVED** [review]

**Pull request closed without merging**
